crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("employee.urls")),
]

crud/employee/urls.py
from django.urls import path
from employee import views


urlpatterns = [
    path('emp/', views.emp),
    path('show/', views.show),
    path('edit/<int:id>', views.edit_data, name="edit"),
    path('delete/<int:id>', views.destroy),
]

crud/employee/models.py
from django.db import models
# Create your models here.


class Employees(models.Model):
    eid = models.AutoField(primary_key=True)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)

    class Meta:
        db_table = "employee"

crud/employee/forms.py
from django import forms
from employee.models import Employees


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employees
        fields = "__all__"

crud/employee/views.py
from django.shortcuts import render, redirect
from employee.forms import EmployeeForm
from employee.models import Employees
from django.core.paginator import Paginator
# Create your views here.


def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)

        if form.is_valid():
            try:
                form.save()
                return redirect("/show")
            except Exception as e:
                print(e)
    else:
        form = EmployeeForm()
    return render(request, "index.html", {"form": form})


def show(request):
    employees = Employees.objects.all().order_by('eid')
    paginator = Paginator(employees, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(request, "show.html", {"page_obj": page_obj})


def edit_data(request, id):
    employee = Employees.objects.get(eid=id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, "edit.html", {"employee": employee})


def destroy(request, id):
    employee = Employees.objects.get(eid=id)
    employee.delete()
    return redirect("/show")

crud/templates/base.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Employee Records</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <style>
        h1{text-align: center;}
        body
        {
        margin-left: 2%;
        margin-top: 10%;
        background-image: url('/static/img/0.jpg');
        background-repeat: no-repeat;
        background-size: 100%;
        }
    </style>

    <script src="{% static 'js/jquery.js' %}" ></script>
    <script src="{% static 'js/bootstrap.js' %}" ></script>
    <script src="{% static 'js/popper.js' %}" ></script>
</head>  
<body> 
{% block content %}
{% endblock %}
</body>  
</html>  

crud/templates/confirm_delete_modal.html
<!–Delete button will redirect to the href of the element with 'id = caller-id' property in this modal–>
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" caller-id="" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body confirm-delete">
        This action is permanent!
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal" id="confirmDeleteButtonModal">Proceed</button>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
            $(document).on('click', '.confirm-delete', function () {
        $("#confirmDeleteModal").attr("caller-id", $(this).attr("id"));
        });

        $(document).on('click', '#confirmDeleteButtonModal', function () {
        var caller = $("#confirmDeleteButtonModal").closest(".modal").attr("caller-id");
        window.location = $("#".concat(caller)).attr("href");
        });
</script>

crud/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <style>
        body
        {
        margin-left: 35%;
        margin-top: 10%;
        background-image: url('/static/img/0.jpg');
        background-repeat: no-repeat;
        background-size: 100%;
        }
    </style>
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{ employee.eid }}">  
        {% csrf_token %}  
          <div class="container">  
      <br>  
                  <div class="form-group row">  
                    <label class="col-sm-1 col-form-label"></label>  
                    <div class="col-sm-4">  
                      <h3>Update Details</h3>  
                    </div>  
                  </div> 
                <div class="form-group row">  
                  <label class="col-sm-2 col-form-label">Employee Name:</label>  
                  <div class="col-sm-4">  
                      <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
                  </div>  
                </div>  
                  <div class="form-group row">  
                  <label class="col-sm-2 col-form-label">Employee Email:</label>  
                  <div class="col-sm-4">  
                      <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
                  </div>  
                </div>  
                  <div class="form-group row">  
                  <label class="col-sm-2 col-form-label">Employee Contact:</label>  
                  <div class="col-sm-4">  
                      <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
                  </div>  
                </div>  
                  <div class="form-group row">  
                  <label class="col-sm-1 col-form-label"></label>  
                  <div class="col-sm-4">  
                  &nbsp&nbsp&nbsp&nbsp<button type="submit" class="btn btn-success">Update</button>  
                  </div>  
                </div>  
          </div>  
</form>  
</body>  
</html>  

crud/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <style>
      body
        {
        font-size: 20px;
        margin-left: 35%;
        margin-top: 10%;
        background-image: url('/static/img/0.jpg');
        background-repeat: no-repeat;
        background-size: 100%;
        }
    </style>
</head>  
<body>  
<form method="POST" class="post-form" action="">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h1>Enter Details</h1> <br/>
    </div>  
  </div>  
       
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Name:</label>  
    <div class="col-sm-4">  
      {{ form.ename }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Employee Email:</label>  
    <div class="col-sm-4">  
      {{ form.eemail }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Contact:</label>  
    <div class="col-sm-4">  
      {{ form.econtact }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

crud/templates/show.html
 
{% extends 'base.html' %}
{% block content %}
<h1>Employee Details</h1><br/>
<table class="table table-hover">   <!-- "table table-striped table-bordered table-sm" -->
    <thead class="thead-dark">  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Email</th>  
        <th>Employee Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody id = 'tbody'>  
{% for employee in page_obj %}  
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.eemail }}</td>  
        <td>{{ employee.econtact }}</td>  
        <td>  
            {% include 'confirm_delete_modal.html' %}
            {% include 'edit.html' %}
            <button type="button" class="btn btn-warning"><a href="/edit/{{ employee.eid }}" data-toggle="modal" data-target="#EditModal" class="confirm-edit" data-sid="{{ employee.eid }}">Edit</a>  </button>
            <button type="button" class="btn btn-danger"> <a href="/delete/{{ employee.eid }}"   class="confirm-delete" title="Delete" data-toggle="modal" data-target="#confirmDeleteModal" id='{{ employee.eid }}'>Delete </a>  </button>
        </td>  
    </tr>

            
{% endfor %}  
    </tbody>  
</table>  

                        {% if page_obj.has_other_pages %}
                            <ul class= "pagination">
                                {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                                {% else %}
                                <li class="disabled"><span>&laquo;</span></li>
                                {% endif %}
                                {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                {% else %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                                {% else %}
                                <li class="disabled"><span>&raquo;</span></li>
                                {% endif %}
                            </ul>
                        {% endif %}
<br>  
<br>  
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>  
{% endblock %}